# CMake generated Testfile for 
# Source directory: C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads
# Build directory: C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/Tests/FindThreads
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[FindThreads.C-only]=] "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/bin/ctest" "--build-and-test" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/C-only" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/Tests/FindThreads/C-only" "--build-generator" "MinGW Makefiles" "--build-makeprogram" "C:/MinGW/bin/mingw32-make.exe" "--build-project" "FindThreads_C-only" "--build-options" "--test-command" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/bin/ctest" "-V")
set_tests_properties([=[FindThreads.C-only]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/CMakeLists.txt;2;add_test;C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/CMakeLists.txt;0;")
add_test([=[FindThreads.CXX-only]=] "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/bin/ctest" "--build-and-test" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/CXX-only" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/Tests/FindThreads/CXX-only" "--build-generator" "MinGW Makefiles" "--build-makeprogram" "C:/MinGW/bin/mingw32-make.exe" "--build-project" "FindThreads_CXX-only" "--build-options" "--test-command" "C:/Users/leesj/Desktop/DiscordBot/src/reversi/builds/bin/ctest" "-V")
set_tests_properties([=[FindThreads.CXX-only]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/CMakeLists.txt;2;add_test;C:/Users/leesj/Desktop/DiscordBot/src/reversi/opencv_sources/cmake-3.21.0-rc1/cmake-3.21.0-rc1/Tests/FindThreads/CMakeLists.txt;0;")
